### PR TITLE
Change email identification to IDs (flarum/core#897)

### PR DESCRIPTION
**Pull request by dav-is**

### CODE REVIEW

**Comment by tobyzerner** [comment]
Forgive me because the issue is not fresh in my mind (and there's a lot to read in #897), but what's the rationale behind this change?

One flaw I see is that since the email is no longer used as "identification", if you already have an existing Flarum account with your fb email address, it's now impossible to log into it via Facebook. If you tried to do so, you'd be presented with the registration form and then you'd have to change the suggested email address to something that's not taken.

Storing the facebook ID is probably a good idea in general, but not necessarily as the sole identifier...

**Comment by dav-is** [comment]
This is the way it works for the GitHub Auth if I'm not mistaken. Emails can't be relied on for an identifier. They change and are seen as such. If someone changes their email on Facebook, what happens then? The id is a static attribute, and should be used as the sole identifier (it's literally called ID as in identification if that's not evidence enough).

**Comment by tobyzerner** [comment]
> This is the way it works for the GitHub Auth if I'm not mistaken. Emails can't be relied on for an identifier.

I think you mean Twitter Auth - that's correct, but it's only the case because the Twitter API doesn't actually allow us to get the user's email, so we have to make them enter it manually.

> If someone changes their email on Facebook, what happens then? 

Good point, and I'm not saying we shouldn't make use of the Facebook ID at all - I'm just saying that it's crap UX when I'm unable to link my existing Flarum account with my Facebook account to make logins easier for myself in the future. Matching emails is one way to do this. I'm sure there are other ways we can think of too. Food for thought.

**Comment by dav-is** [comment]
> link my existing Flarum account with my Facebook account

This is almost always done by signing into Facebook while signed into a service's account. 

Your idea poses a security risk as well. Say a user creates a Flarum account, they don't have a Facebook account. Someone signs up for a Facebook account with that user's email address and uses that to sign into the first user's Flarum account. This is only possible is Facebook fails to confirm the email. This might not be a huge issue as Facebook is relatively trustworthy, but an issue that could be huge for a different SSO provider. It's best for unity in the way that SSO is handled in Flarum so that the issue you mentioned can be fixed across the board.

**Comment by tobyzerner** [comment]
Done with b8 release

**Pull request closed without merging**
